version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE_NAME}
    env_file:
      - ./.env
    volumes:
      - mongo:/data/db
    ports:
      - '6000:27017'

  auth:
    image: ghcr.io/apoorva64/express-jwt-auth/v1:latest
    container_name: auth
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      - MONGODB_URL=mongodb://auth:password123@mongo:27017/auth?authSource=admin
    ports:
      - '8000:8000'
    volumes:
      - ./keys:/usr/app/keys
    entrypoint: ['./start.sh']
volumes:
  mongo:

